module AwsHelpers

  UPDATE_ROLLBACK_COMPLETE = 'UPDATE_ROLLBACK_COMPLETE'
  CREATE_COMPLETE = 'CREATE_COMPLETE'
  ROLLBACK_FAILED = 'ROLLBACK_FAILED'
  ROLLBACK_COMPLETE = 'ROLLBACK_COMPLETE'
  UPDATE_COMPLETE = 'UPDATE_COMPLETE'

end